import type { Metadata } from 'next';
import { Toaster as Sonner } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { NextIntlClientProvider } from 'next-intl';
import { getCookie } from '@/lib/cookies';
import { shadcnLightTheme } from '@/components/constants/themeConfig';
import { getLocale } from 'next-intl/server';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const theme = await getCookie(
    process.env.NEXT_PUBLIC_THEME_COOKIE!,
    shadcnLightTheme,
  );
  return (
    <html lang={locale} className={theme} style={{ colorScheme: theme }}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme={theme}
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </ThemeProvider>
        <Sonner richColors visibleToasts={5} />
      </body>
    </html>
  );
}
